name: Daily question
description: try to resolve& pull request !
title: "day "
labels: ["❔ Question"]
assignees:
  - junnyJun
body:
- type: textarea
  id: repro
  attributes:
    label: Today's
    description: "try to resolve& pull request !"
    value: |
      1. [Q1]()
      2. [Q2]()
      3. [Q3]()
      4. [Q3]()
    render: bash
  validations:
    required: true
