name: Daily question
description: try to resolve& pull request !
title: "[{{date}}]: "
labels: ["❔ Question"]
assignees:
  - junnyJun
body:
  - type: input
    id: contact
    attributes:
      label: Q 1
      placeholder: Please input leetcode Link
    validations:
      required: false      
  - type: input
    id: contact      
    attributes:
      label: Q 2
      placeholder: Please input leetcode Link
    validations:
      required: false      
  - type: input
    id: contact      
    attributes:
      label: Q 3
      placeholder: Please input leetcode Link
    validations:
      required: false      
  - type: input
    id: contact      
    attributes:
      label: Q 4
      placeholder: Please input leetcode Link
    validations:
      required: false



