name: Daily question
description: try to resolve& pull request !
title: ""
labels: ["❔ Question"]
assignees:
  - junnyJun
body:
  - type: input
    id: q1
    attributes:
      label: Q 1
      placeholder: Please input leetcode Link
    validations:
      required: false      
  - type: input
    id: q2      
    attributes:
      label: Q 2
      placeholder: Please input leetcode Link
    validations:
      required: false      
  - type: input
    id: q3      
    attributes:
      label: Q 3
      placeholder: Please input leetcode Link
    validations:
      required: false      
  - type: input
    id: q4      
    attributes:
      label: Q 4
      placeholder: Please input leetcode Link
    validations:
      required: false



