name: Daily question
description: try to resolve& pull request !
title: "day "
labels: ["❔ Question"]
assignees:
  - junnyJun
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      (Q1)[]
      (Q2)[]
      (Q3)[]
      (Q4)[]
      (Q5)[]



